title: Md. Khairul Basar
logo: /assets/images/Circle official.png
description: Passionate Industrial & Production Engineering student with leadership experience in team projects. Skilled in Excel, VBA, data science, and machine learning, with a focus on optimizing operations and supply chains for efficiency and productivity.
#show_downloads: true
theme: jekyll-theme-minimal
