title: Md. Khairul Basar
logo: /assets/images/Circle official.png
description: Passionate Industrial & Production Engineering student with leadership experience in **team-based projects**. Skilled in **Excel, VBA, data science, and machine learning**. Interested in **operations** and **supply chain management**, aiming to enhance efficiency and productivity through problem-solving and analytical skills.
#show_downloads: true
theme: jekyll-theme-minimal
